[package]
name = "rsbuild"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Tool to build projects."

[dependencies]
colored = "2.0.0"
command-macros = "0.2.9"
compose_yml = "0.0.59"
debug_print = "1.0.0"
eval = "0.4.3"
foreach = "0.3.0"
lazy_static = "1.4.0"
serde_any = "0.5.0"
